### ISSUE TITLE
dotfiles video on youtube :-)

### ISSUE THREAD

**Issue by serapath** [jrock2004/dotfiles#6]
hey, i stumbled upon your video from january 2017 on youtube.
* https://www.youtube.com/watch?v=-aSHeEGVrLo

In that you talk about `install.sh` and how you automate a lot of things, but you don't seem to have those anymore.
* why is it not in the repo anymore?
* how do you do things these days?

thx for the video. it inspired me :-)

**Comment by jrock2004** [comment]
Thanks for watching. I have moved that code to it’s own repo. jrock2004/install-scripts
